import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  BookOpen,
  BriefcaseBusiness,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  CircleUserRound,
  Dumbbell,
  Flame,
  Gem,
  GraduationCap,
  Hand,
  HandHeart,
  Heart,
  HeartHandshake,
  Lightbulb,
  LockKeyhole,
  Menu,
  MessagesSquare,
  MousePointerClick,
  PartyPopper,
  PersonStanding,
  Rocket,
  Sparkles,
  Stethoscope,
  Target,
  Trophy,
  UsersRound,
} from "lucide-react";

const ICONES = Object.freeze({
  accessibility: Accessibility,
  account_circle: CircleUserRound,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_forward_ios: ArrowRight,
  auto_awesome: Sparkles,
  celebration: PartyPopper,
  check: CircleCheck,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  diamond: Gem,
  diversity_3: HeartHandshake,
  emoji_events: Trophy,
  family_restroom: UsersRound,
  favorite: Heart,
  fitness_center: Dumbbell,
  forum: MessagesSquare,
  hand_heart: HandHeart,
  leaderboard: BarChart3,
  lightbulb: Lightbulb,
  local_fire_department: Flame,
  lock: LockKeyhole,
  menu: Menu,
  menu_book: BookOpen,
  person: CircleUserRound,
  rocket_launch: Rocket,
  school: GraduationCap,
  self_improvement: PersonStanding,
  sign_language: Hand,
  stethoscope: Stethoscope,
  target: Target,
  touch_app: MousePointerClick,
  track_changes: Target,
  waving_hand: Hand,
  work: BriefcaseBusiness,
});

/** Ícones SVG do Lucide, dimensionados pelas classes `text-*` do Tailwind. */
export function AppIcon({ nome, className = "", preenchido = false, ...props }) {
  const Icone = ICONES[nome] ?? CircleHelp;

  return <Icone aria-hidden="true" strokeWidth={2.5} className={`size-[1em] shrink-0 ${preenchido ? "fill-current" : ""} ${className}`.trim()} {...props} />;
}
